import type { PortfolioPreset } from './types';

export const portfolioPresets: PortfolioPreset[] = [
  {
    id: 'standard',
    name: 'スタンダード型',
    subtitle: '4資産均等配分のオーソドックスな構成',
    allocations: [
      { category: '国内株式', weight: 0.25 },
      { category: '国内債券', weight: 0.25 },
      { category: '先進国株式', weight: 0.25 },
      { category: '海外債券', weight: 0.25 },
    ],
    expectedReturn: 6.5,
    risk: 5.46,
    color: 'blue',
  },
  {
    id: 'standard-risk-reduced',
    name: 'スタンダード型＋リスク軽減',
    subtitle: '4資産ベース＋REIT・コモディティで分散強化',
    allocations: [
      { category: '国内株式', weight: 0.2125 },
      { category: '国内債券', weight: 0.2125 },
      { category: '先進国株式', weight: 0.2125 },
      { category: '海外債券', weight: 0.2125 },
      { category: 'REIT', weight: 0.05 },
      { category: 'コモディティ', weight: 0.10 },
    ],
    expectedReturn: 7.75,
    risk: 5.30,
    color: 'cyan',
  },
  {
    id: 'standard-return-boost',
    name: 'スタンダード型＋リターン追求',
    subtitle: '4資産ベース＋REIT・新興国株で収益性向上',
    allocations: [
      { category: '国内株式', weight: 0.2125 },
      { category: '国内債券', weight: 0.2125 },
      { category: '先進国株式', weight: 0.2125 },
      { category: '海外債券', weight: 0.2125 },
      { category: 'REIT', weight: 0.10 },
      { category: '新興国株式', weight: 0.05 },
    ],
    expectedReturn: 8.76,
    risk: 6.00,
    color: 'indigo',
  },
  {
    id: 'stable-return-boost',
    name: '安定型＋リターン追求',
    subtitle: '債券重視の安定運用にリターン要素をプラス',
    allocations: [
      { category: '国内株式', weight: 0.14 },
      { category: '国内債券', weight: 0.53 },
      { category: '先進国株式', weight: 0.14 },
      { category: '海外債券', weight: 0.09 },
      { category: 'REIT', weight: 0.04 },
      { category: 'コモディティ', weight: 0.06 },
    ],
    expectedReturn: 5.59,
    risk: 3.27,
    color: 'green',
  },
  {
    id: 'aggressive-risk-reduced',
    name: '積極運用型＋リスク軽減',
    subtitle: '株式中心の積極配分にREIT・コモディティで安定性',
    allocations: [
      { category: '国内株式', weight: 0.48 },
      { category: '国内債券', weight: 0.08 },
      { category: '先進国株式', weight: 0.08 },
      { category: '海外債券', weight: 0.16 },
      { category: 'REIT', weight: 0.10 },
      { category: 'コモディティ', weight: 0.10 },
    ],
    expectedReturn: 11.44,
    risk: 7.80,
    color: 'orange',
  },
  {
    id: 'aggressive-return-boost',
    name: '積極運用型＋リターン追求',
    subtitle: '株式中心に新興国も加えた最大リターン狙い',
    allocations: [
      { category: '国内株式', weight: 0.48 },
      { category: '国内債券', weight: 0.08 },
      { category: '先進国株式', weight: 0.08 },
      { category: '海外債券', weight: 0.16 },
      { category: 'REIT', weight: 0.10 },
      { category: '新興国株式', weight: 0.10 },
    ],
    expectedReturn: 12.66,
    risk: 8.90,
    color: 'red',
  },
];
